
import Header from "./_components/header";
import { I18nProvider } from "./_i18n/i18n-provider";
import { ThemeProvider } from './_theme/theme-provider';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <I18nProvider>
          <ThemeProvider>
            <Header/>
            {children}
            </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
